set nocompatible

autocmd!
set backspace=indent,eol,start

set autoindent
set autowrite
set textwidth=0
set showcmd
set encoding=utf-8
set fileencoding=utf-8

set showmatch
set ignorecase
set smartcase
set hlsearch
set incsearch

set wildmenu
set wildmode=list:longest

set history=10000
set viminfo='20,\"50

set showcmd
set ruler				" always show the cursor position
set title

" I like tabs
set softtabstop=4
set tabstop=4
set shiftwidth=4
