set nocompatible

set runtimepath^=~/.vim/pack/plugins/start/vim-vue/syntax/vue.vim

autocmd!
set backspace=indent,eol,start

set autoindent
set autowrite
set textwidth=0
set showcmd
set encoding=utf-8
set fileencoding=utf-8
set number

set showmatch
set ignorecase
set smartcase
set hlsearch
set incsearch

set wildmenu
set wildmode=list:longest

set nobackup
set history=5000
set laststatus=2
set ruler
set title

set expandtab
set softtabstop=2
set tabstop=2
set shiftwidth=2

set foldmethod=indent
set foldnestmax=3
set nofoldenable
set foldlevel=1

nmap <C-J> a<CR><ESC>

filetype plugin indent on
syntax on
colors tomorrownight-bright

" au BufRead,BufNewFile *.less set filetype=css
au BufRead,BufNewFile *.vue set filetype=html
au BufRead,BufNewFile *.less set filetype=less
au BufRead,BufNewFile *.ts set filetype=typescript

augroup myvimrc
  au!
  au BufWritePost .vimrc so $MYVIMRC | if has ('gui_running') | so $MYGVIMRC | endif
augroup END

function! MakeSession()
  let b:sessiondir = $HOME . "/.vim/sessions" . getcwd()
  if (filewritable(b:sessiondir) != 2)
    exe 'silent !mkdir -p ' b:sessiondir
    redraw!
  endif
  let b:filename = b:sessiondir . '/session.vim'
  exe "mksession! " . b:filename
endfunction

function! LoadSession()
  let b:sessiondir = $HOME . "/.vim/sessions" . getcwd()
  let b:sessionfile = b:sessiondir . "/session.vim"
  if (filereadable(b:sessionfile))
    exe 'source ' b:sessionfile
  else
    echo "No session loaded."
  endif
endfunction
